# Generated by Django 3.1.7 on 2021-03-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210316_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_first_name',
            new_name='default_full_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_last_name',
        ),
    ]
