# Generated by Django 3.1.7 on 2021-03-22 14:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20210322_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.5'), max_digits=6),
        ),
    ]
