# Generated by Django 3.1.7 on 2021-02-24 13:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('rrp', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Recommended Retail Price')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(null=True, upload_to='products/static/product_img')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('product_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductGender',
            fields=[
                ('product_gender_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Product Genders',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('product_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Product Types',
            },
        ),
        migrations.CreateModel(
            name='ProductSizesQuantity',
            fields=[
                ('product_sizes_quantity_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=254)),
                ('quantity', models.PositiveIntegerField()),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Product Sizes & Quantities',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productgender'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.producttype'),
        ),
    ]
