# Generated by Django 3.1.7 on 2021-02-24 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210224_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSizesStock',
            fields=[
                ('product_sizes_quantity_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=254)),
                ('stock', models.PositiveIntegerField()),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Product Sizes & Quantities',
            },
        ),
        migrations.DeleteModel(
            name='ProductSizesQuantity',
        ),
    ]
