# Generated by Django 3.1.7 on 2021-02-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210224_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/static/                                  product_img/placeholder.jpg', upload_to='product_img/'),
        ),
    ]
