# Generated by Django 3.1.7 on 2021-03-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210303_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/static/                                   product_img/placeholder.jpg', upload_to='static/product_img/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('select type', 'SELECT TYPE'), ('shorts', 'SHORTS'), ('gloves', 'GLOVES'), ('shin guards', 'SHIN GUARDS'), ('mouth guards', 'MOUTH GUARDS'), ('handwraps', 'HANDWRAPS'), ('gi', 'GI'), ('belts', 'BELTS'), ('rash guards', 'RASH GUARDS'), ('spats', 'SPATS'), ('groin guards', 'GROIN GUARDS'), ('kick shields', 'KICK SHIELDS'), ('belly pads', 'BELLY PADS'), ('punch bags', 'PUNCH BAGS'), ('grappling dummies', 'GRAPPLING DUMMIES'), ('joint support', 'JOINT SUPPORT')], default='SELECT TYPE', max_length=20),
        ),
    ]
