# Generated by Django 3.1.7 on 2021-03-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210308_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsizesstock',
            options={'verbose_name_plural': 'Product Sizes and Stock'},
        ),
        migrations.AlterField(
            model_name='productsizesstock',
            name='size',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
