# Generated by Django 3.1.7 on 2021-03-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20210325_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsizesstock',
            old_name='product_sizes_quantity_id',
            new_name='product_sizes_stock_id',
        ),
    ]
