# Generated by Django 3.1.7 on 2021-03-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210326_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsizesstock',
            name='size',
            field=models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('false', 'FALSE')], max_length=10, null=True),
        ),
    ]
